### PR TITLE
Improved the performance of the initial tree rendering

### PR DESCRIPTION
**Pull request by skateman**
**Before:**
before

**After:**
after

More detailed profiling data is available in the [upstream PR](https://github.com/jonmiles/bootstrap-treeview/pull/287).

### CODE REVIEW

**Comment by kbrock** [comment]
This is great. Will make a big improvement to our screens

**Comment by priley86** [comment]
@bleathem would you be OK with including this in our next release? I will do another publish for this...

**Comment by priley86** [comment]
+1 great work @skateman

**Comment by martinpovolny** [comment]
I am still a bit concerned about 672ae63ff1f1ada6efee58fd1d16fbca37074f38 
Why it was done that way insted of the simple way. Could have been some valid reason for that?

**Comment by skateman** [comment]
Yup, forgot to mention in the description. We were checking this with @himdel and @martinpovolny and couldn't find any reason. Could you pf people look into it?

**Comment by priley86** [comment]
I've pulled this branch down and test locally with our tree pages in p.f. 

Code looks much better, hopefully upstream will notice it. Happy to see this merged.

**Comment by priley86** [comment]
confirmed with @skateman this is ready for merge.

**Comment by kbrock** [comment]
thank you @priley86

**Pull request merged**
