### PR TITLE
Changes tagsClass definition format

### PR DESCRIPTION
**Pull request by Zehir**
Hello,

Previously in bootstrap-treeview;
I add the possibility to add an option to set the classes of each nodes. (#34)
Then we get an unexpected result in special case (#37) and (#41)
I made a fix for this issue (#39) but @skateman, @himdel was not happy about this mystical link between tags and tagClasses option.

Today I make this new pull request to fix all this with A new format.
tagsClass is always A string.
tags can be an array of string like before but can also be an array of object like this (or mixed strings and objects):
```javascript
{text: 'Danger !', class: 'label label-danger'}
```
 I made a [jsfiddle](https://jsfiddle.net/Zorim/yka0yaq7/) if you want to check the usage. 

PS: #42 was just a miss click

### CODE REVIEW

**Comment by skateman** [comment]
I like this one, @himdel what do you think?

**Comment by Zehir** [comment]
This format allow more options if we need to add them later like dataAttr, id,...

**Comment by Zehir** [comment]
If this PR il merged, I will probably do an other one to add these options;
- dataAttr
- id
- icon
- color
- backColor
- link (allow tag to by clikable)
- linkTarget (_top or _blank)
And maybe an order definition (from left to right) default value is the order of object from right to left.
@skateman What do you think about this?

**Comment by himdel** [comment]
I think this looks great, it preserves the original functionality - providing just `tags: ["4"]` will use text `4` and class `badge` - and allows simple customization per-tag, per-node *and* per-tree. :+1: 

@Zehir not sure icon, color, etc. aren't better expressed using css classes which we already can do, but in general that definitely makes sense :) (and you may have a use case for colors too :))

**Comment by Zehir** [comment]
Ok so just for dataAttr, link and linkTarget.
I just add the other to match the node definition.

**Comment by skateman** [comment]
@Zehir I'm pretty sure I already added the support for the `id` and `class` attributes. The `icon` was available before I took over the project and the `color` doesn't really make sense if you have the `class` attribute. Also the `link` should be handled through the existing `onNodeSelected`.

I did something like `data-click` in a toolbar in an other project and that has been evaluated by `onClick`. This way you would need only the `dataAttr` :wink:

**Comment by himdel** [comment]
@skateman Those are on node, not on a badge, pretty sure Zehir wanted to add those properties to the badge object.. (so, I don't think `onNodeSelected` solves `link`..)

**Comment by Zehir** [comment]
Yes but you cannot define multiple link for different tags. Therefore, to be simple, I can add the dataAttr on tag and onTagClick event.

**Comment by skateman** [comment]
You simply can determine the event's target in the `onNodeSelected`:
```js
onNodeSelected: function (e) {
  if ($(e.target) == $('.badge')) { // I'm pretty sure this comparison would not work, but you need something like this
    do_something();
  }
}
```

Anyway, the thing you want to introduce is a major change for now and I'd rather avoid it for a little longer. We're planning to [componentize](https://www.webcomponents.org/) the treeview in a new major version that could allow such big changes.

**Comment by Zehir** [comment]
OK I see. So only dataAttr on tag ?
And what about sort tags?

**Comment by skateman** [comment]
Ah you're talking about `dataAttr` on a tag, don't think that's necessary if you work with the onNodeSelected I described above. I thought I haven't added the `dataAttr` on a node...

I don't understand this "sort tags" thing, can you be more specific?

**Comment by Zehir** [comment]
For exemple if we have this:
tags: ['1', '2', '3', '4'],
The display is: 4 3 2 1
[jsfiddle](https://jsfiddle.net/Zorim/yka0yaq7/)
Instead of reverse the source array we can define the numeric index of tag

**Comment by skateman** [comment]
The tags are ordered properly as you have them in the list, but the `.pull-right` class causes them to appear in reverse order. We can't do anything about that, it's a bootstrap-thing :disappointed:. I'd suggest to sort+reverse while generating the JSON.

**Comment by Zehir** [comment]
Oh this explains everything.
Thank you

**Comment by Zehir** [comment]
Can you make a new release with this PR and close #37 and #41 ?

**Pull request merged**
