### PR TITLE
removes bower install

### PR DESCRIPTION
**Pull request by priley86**
* address issue noted by Vojtech Szocs in Patternfly ML

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by dgutride** [comment]
Looks good

**Comment by priley86** [comment]
thanks @dgutride !

**Comment by vojtechszocs** [comment]
Nice! This means `npm install patternfly` won't result in npm warning when Bower isn't installed.

Quote from [npm docs](https://docs.npmjs.com/misc/scripts#best-practices) on `install` script:

> The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture.

**Pull request merged**
