### PR TITLE
Fixed lazy-loading when calling expandNode()

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by priley86** [comment]
Tested this fix in P.F. lazy-load example. Let's merge.

**Comment by priley86** [comment]
@bleathem can you merge please?

**Comment by bleathem** [comment]
Thanks for the functional review @priley86

**Comment by bleathem** [comment]
@skateman can you rebase?

**Comment by priley86** [comment]
+1, @skateman if you will rebase, we can merge and tag a new version of treeview in tomorrow's release.

**Comment by skateman** [comment]
@bleathem @priley86 done

**Comment by priley86** [comment]
@skateman the rebase looks good. merging this and publishing a new tag.

**Comment by dtaylor113** [comment]
Glad to see this fixed, thanks!   So MiQ SSUI doesn't specifically get patternfly-bootstrap-treeview, just patternfly (of which patternfly-bootstrap-treeview is a dependency).  So, in order to get this fix into MiQ SSUI it sounds like I'll need to wait for the next version of patternfly (3.10.1?), which will have the latest version number of patternfly-bootstrap-treeview (2.0.2?).  Are my assumptions correct?  -thanks!

**Comment by dtaylor113** [comment]
Hi, still seeing this issue.  Please see issue raised in 'patternfly-bootstrap-treeview': [CollapseAll and ExpandNode doesn't seem to work](https://github.com/patternfly/patternfly-bootstrap-treeview/issues/14)

**Pull request merged**
