### PR TITLE
Update bower/npm for new dependency

### PR DESCRIPTION
**Pull request by priley86**
* create our forks new npm/bower 

Note: will need to rebase #1 after

### CODE REVIEW

**Comment by priley86** [comment]
@bleathem let me know if this works! I held off from changing any dependencies as they will be changed in PR #1 . Also - was curious if you'd like to see PR #1 split up in our future effort, or merged this sprint?

**Comment by bleathem** [comment]
I thought twice about the version reset to 1.0.0, but I feel it makes sense as we will get into a mess if we try and track the upstream version.

:+1: let's merge

**Comment by priley86** [comment]
@dtaylor113 @dlabrecq any chance you can review this and merge if OK? Will add a follow up PR in P.F. for referencing our new fork after it's published to npm. I think that's the only goal with bootstrap-treeview this sprint.

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by priley86** [comment]
@jeff-phillips-18 thanks! I owe you one

**Pull request merged**
