### PR TITLE
Fix the undefined issue with showTags

### PR DESCRIPTION
**Pull request by Zehir**
Fixes for #37

### CODE REVIEW

**Comment by Zehir** [comment]
I made a [jsfiddle](https://jsfiddle.net/Zorim/a8w72c9v/1/) if you want to see.
``` javascript
$(function() {
  var defaultData = [{
    text: 'Parent 1',
    href: '#parent1',
    tags: ['4'],
    // It's a number so we set the badge class
    tagsClass: ['badge'],
    nodes: [{
      text: 'Child 1 with two tags',
      href: '#child1',
      tags: ['danger','warning'],
      // define the class like the text, danger in red and warning in orange
      tagsClass: ['label label-danger','label label-warning'],
      nodes: [{
        text: 'Grandchild 1 with one tag',
        href: '#grandchild1',
        tags: ['danger'],
        // Even with one tag the tagsClass should be a array
        tagsClass: ['label label-danger']
      }, {
        text: 'Grandchild 2 with one other tag',
        href: '#grandchild2',
        tags: ['warning'],
        tagsClass: ['label label-warning']
      }]
    }, {
      text: 'Child 2 with one tag with class and one default',
      href: '#child2',
      tags: ['danger', 'default'],
      // If there is less class than tags the last take the defaults classes
      tagsClass: ['label label-danger']
    }]
  }, {
    text: 'Parent 2 with 3 tag ',
    href: '#parent2',
    tags: ['default','primary','success'],
    // you can define by order the class, the missing one take de default value
    tagsClass: {1:'label label-primary',2:'label label-success'}
  }];

  var $checkableTree = $('#treeview-checkable').treeview({
    data: defaultData,
    showTags: true,
    tagsClass: 'label label-default'
  });
});

```

**Comment by skateman** [comment]
Hm, this one looks pretty complicated for me. I'd rather go with a single *master* class in the global definition and explicit classes for every other case...those class names aren't so long.

**Comment by Zehir** [comment]
@skateman May be we can allow tagsClass on node to be string, all tags of this node take this class and a callback to define the class based on value like this:
```javascript
tagsClass: function (v) {
    switch (typeof v) {
        case 'number':
            return 'badge';
            break;
        case 'string':
            if (['default', 'primary', 'success', 'info', 'warning', 'danger'].indexOf(v) !== -1) {
                return 'label label-' + v;
            }
            break;
    }
    return null;
},
```
if null we take the default value or badge (template)

**Comment by Zehir** [comment]
With my correction all case works for now

**Comment by skateman** [comment]
I understand your idea, but I'd rather go with the simplest approach where you have 2 levels of setting a value: global, local. This is how it is for every other parameter and I don't see the point on breaking this logic.

**Comment by Zehir** [comment]
This option use the same logic as tags

**Comment by Zehir** [comment]
If you want the same structure for the local and global options we just have to add the condition if it is a string the value is used for all strings

**Comment by skateman** [comment]
Hm @himdel, what do you think about this?

**Comment by himdel** [comment]
Hm.. not sure any backward compatibility issues, etc., but:

   * the array syntax just looks wrong, any code that assumes `array1[3]` is somehow related to `array2[3]` should just be shot :). Either use the tag name as a key to the class object, or add a single place to provide tag definitions, and then you don't have to do that and can just give a list of tags to use.

   * for this use case, it seems like every time you use `danger`, you also use `label label-danger`. Therefore, repeating this over and over again sounds just broken.


So..

What about doing something like this?

```
$(function() {
  var defaultData = [{
    text: 'Parent 1',
    href: '#parent1',
    tags: ['number'],
    nodes: [{
      text: 'Child 1 with two tags',
      href: '#child1',
      tags: ['danger','warning'],
      nodes: [{
        text: 'Grandchild 1 with one tag',
        href: '#grandchild1',
        tags: ['danger'],
      }, {
        text: 'Grandchild 2 with one other tag',
        href: '#grandchild2',
        tags: ['warning'],
      }]
    }, {
      text: 'Child 2 with one tag with class and one default',
      href: '#child2',
      tags: ['danger', 'default'],
    }]
  }, {
    text: 'Parent 2 with 3 tag ',
    href: '#parent2',
    tags: ['default','primary','success'],
  }];

  var tags = {
    default: { label: "default", class: "label label-danger" },
    primary: { label: "primary", class: "label label-primary" },
    success: { label: "success", class: "label label-success" },
    warning: { label: "warning", class: "label label-warning" },
    danger: { label: "danger", class: "label label-danger" },
    number: { label: "4", class: "badge" },
    [undefined]: 'label label-default',  // default value (or just another treeview param?)
  };

  var $checkableTree = $('#treeview-checkable').treeview({
    data: defaultData,
    showTags: true,
    tags: tags,
  });
});
```

Then, the code can simply do `item.tags.forEach(function(tag) { $(...).append(options.tags[tag].label).addClass(options.tags[tag].class || options.tags[undefined]); }`, no extra code needed.

And if by any chance you *really* need a specific element's tag styled differently than the other tags of the same value, you can always do custom css depending on the tree *item*'s custom class..

**Comment by Zehir** [comment]
You do the same abstract link, you have the keys in node and the values in "tags"
Maybe we can do this:


```javascript
    $(function () {

        var tagsTemplate = {
            warning: {label: "warning", class: "label label-warning"},
            primary: {label: "primary", class: "label label-primary"}
        };
        
        var defaultData = [{
            text: 'Parent 1',
            href: '#parent1',
            tags: [{label: "default", class: "label label-default"}],
            nodes: [{
                text: 'Child 1 with two tags',
                href: '#child1',
                tags: [
                    {label: "danger", class: "label label-danger"},
                    {label: "warning", class: "label label-warning"}
                ],
                nodes: [{
                    text: 'Grandchild 1 with one tag',
                    href: '#grandchild1',
                    tags: ['default']
                }, {
                    text: 'Grandchild 2 with one other tag',
                    href: '#grandchild2',
                    tags: {'tag 1', 'tag 2'}
                }]
            }, {
                text: 'Child 2 with one tag with class and one default',
                href: '#child2',
                tags: [tagsTemplate['primary'], tagsTemplate['warning']],
            }]
        }, {
            text: 'Parent 2 with 3 tag ',
            href: '#parent2',
            tags: ['default', 'primary', 'success']
        }];

        var $checkableTree = $('#treeview-checkable').treeview({
            data: defaultData,
            showTags: true,
            tagsClass: 'label label-default'
        });
    });
```
We can set one default class values and we can per tag define a class and other options later if we need.
For the backward compatibility we are good because if we keep the ad a string this will use the default class. And if you want you can have a var with tags template. But with my method you can define custom class with lazy load instead of define them in the first load.

**Comment by Zehir** [comment]
So, @skateman, @himdel what we do?

**Pull request closed without merging**
