### PR TITLE
Fixed initial rendering of partially-checked nodes

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by priley86** [comment]
thanks @skateman - from initial glance, this change looks ok to me, but I will pull it down and test it out. 

@bleathem - if we are OK with this change, would be it OK to do a minor bug fix release to `patternfly-bootstrap-treeview` some time this week (i.e. `2.0.1`)?

**Comment by skateman** [comment]
@priley86 good for me

**Comment by dlabrecq** [comment]
LGTM.

**Comment by priley86** [comment]
thanks @dlabrecq

**Comment by priley86** [comment]
+1 this looks fine. LGTM

**Pull request merged**
