### PR TITLE
Implemented onNodeSelected event firing for already selected nodes

### PR DESCRIPTION
**Pull request by skateman**
When `preventUnselect` and `allowReselect` are both enabled,
it is now possible to resend the onNodeSelected event when clicking
on an already selected node.

(cherry picked from commit 5de092efb799139531a51bb26794c3d0a9500a4f)

### CODE REVIEW

**Comment by skateman** [comment]
@priley86 can you review this please?

**Comment by epwinchell** [comment]
@serenamarie125 This is on our functionality to-do list ( https://github.com/ManageIQ/manageiq/pull/11387 ) for our current release.  We're hoping to at least be able to use a new version of patternfly-bootstrap-treeview with this fix.

cc @skateman @dclarizio

**Comment by priley86** [comment]
+1 @skateman for "allowReselect". I've pulled this down and tested it in our PF bootstrap-treeview tests. I'd ask that you get one more reviewer and we can safely merge.

**Comment by bleathem** [comment]
Looks good, merging.

**Pull request merged**
