### PR TITLE
Throw an error when treeview called on a nonexisting element

### LINKED ISSUE #16: $(selector).treeview(true) returns a jquery object when tree not found
Call `$('#nonexistent_tree').treeview(true)`.

You'll get the same object as from `$('#nonexistent_tree')`.

Should probably return null or throw an exception instead..

### PR DESCRIPTION
**Pull request by skateman**
Fixes #16

### CODE REVIEW

**Comment by skateman** [comment]
@himdel will this be good?

**Comment by himdel** [comment]
I think so, yeah :)  thanks

**Comment by skateman** [comment]
@priley86 can you please take a look at this one?

**Comment by priley86** [comment]
@skateman PR looks fine to me. apologies for the delay - somehow missed my inbox and I've been stretched on other work. Do you mind publishing the release here? We can update PF core after...

**Pull request merged**
